/**
 * Auto-generated by scripts/generate-meme-templates.ts
 * Text zones detected by Claude vision API.
 * Do not edit manually — re-run the script instead.
 */
import type { MemeTemplate } from "@/lib/memes/types";

export const memeTemplates: MemeTemplate[] = [
  {
    id: "drake",
    name: "Drake Hotline Bling",
    src: "/memes/drake.jpg",
    width: 1200,
    height: 1200,
    textFields: [
      { id: "top", label: "Drake No", x: 648, y: 48, width: 504, height: 504, fontSize: 48, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "bottom", label: "Drake Yes", x: 648, y: 648, width: 504, height: 504, fontSize: 48, color: "#000000", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "distracted-boyfriend",
    name: "Distracted Boyfriend",
    src: "/memes/distracted-boyfriend.jpg",
    width: 1200,
    height: 800,
    textFields: [
      { id: "woman_red", label: "Woman in Red", x: 36, y: 464, width: 336, height: 192, fontSize: 48, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "distracted_man", label: "Distracted Boyfriend", x: 504, y: 368, width: 252, height: 288, fontSize: 48, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "girlfriend", label: "Disapproving Girlfriend", x: 852, y: 392, width: 276, height: 272, fontSize: 48, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "two-buttons",
    name: "Two Buttons",
    src: "/memes/two-buttons.jpg",
    width: 600,
    height: 908,
    textFields: [
      { id: "button1", label: "Left Button", x: 42, y: 45, width: 204, height: 272, fontSize: 16, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "button2", label: "Right Button", x: 258, y: 36, width: 204, height: 272, fontSize: 16, color: "#000000", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "change-my-mind",
    name: "Change My Mind",
    src: "/memes/change-my-mind.jpg",
    width: 482,
    height: 361,
    textFields: [
      { id: "sign", label: "Sign Text", x: 77, y: 220, width: 323, height: 87, fontSize: 19, color: "#000000", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "expanding-brain",
    name: "Expanding Brain",
    src: "/memes/expanding-brain.jpg",
    width: 857,
    height: 1202,
    textFields: [
      { id: "panel1", label: "First Panel Text", x: 21, y: 24, width: 300, height: 240, fontSize: 26, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "panel2", label: "Second Panel Text", x: 21, y: 325, width: 300, height: 240, fontSize: 26, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "panel3", label: "Third Panel Text", x: 21, y: 625, width: 300, height: 240, fontSize: 26, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "panel4", label: "Fourth Panel Text", x: 21, y: 926, width: 300, height: 240, fontSize: 26, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "woman-yelling-cat",
    name: "Woman Yelling at Cat",
    src: "/memes/woman-yelling-cat.jpg",
    width: 680,
    height: 438,
    textFields: [
      { id: "left", label: "Woman Yelling Text", x: 14, y: 4, width: 313, height: 96, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "right", label: "Cat Text", x: 354, y: 4, width: 313, height: 96, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "one-does-not-simply",
    name: "One Does Not Simply",
    src: "/memes/one-does-not-simply.jpg",
    width: 568,
    height: 335,
    textFields: [
      { id: "top", label: "Top Text", x: 28, y: 17, width: 511, height: 67, fontSize: 30, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "bottom", label: "Bottom Text", x: 28, y: 251, width: 511, height: 67, fontSize: 30, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "success-kid",
    name: "Success Kid",
    src: "/memes/success-kid.jpg",
    width: 500,
    height: 500,
    textFields: [
      { id: "top", label: "Top Text", x: 25, y: 13, width: 450, height: 125, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "bottom", label: "Bottom Text", x: 25, y: 363, width: 450, height: 125, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "is-this-a-pigeon",
    name: "Is This a Pigeon?",
    src: "/memes/is-this-a-pigeon.jpg",
    width: 1587,
    height: 1425,
    textFields: [
      { id: "butterfly", label: "Butterfly (Thing Being Questioned)", x: 1206, y: 86, width: 317, height: 257, fontSize: 42, color: "#000000", outline: true, align: "center", valign: "middle" },
      { id: "person", label: "Person (The Confused One)", x: 63, y: 1040, width: 524, height: 228, fontSize: 42, color: "#000000", outline: true, align: "center", valign: "middle" },
      { id: "question", label: "Question Text", x: 619, y: 428, width: 413, height: 200, fontSize: 48, color: "#000000", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "left-exit-12-off-ramp",
    name: "Left Exit 12 Off Ramp",
    src: "/memes/left-exit-12-off-ramp.jpg",
    width: 804,
    height: 767,
    textFields: [
      { id: "highway_sign", label: "Highway Sign Text", x: 161, y: 69, width: 466, height: 184, fontSize: 32, color: "#FFFFFF", outline: false, align: "center", valign: "middle" },
      { id: "exit_ramp", label: "Exit Ramp Choice", x: 507, y: 422, width: 217, height: 138, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "straight_path", label: "Straight Path Choice", x: 40, y: 430, width: 241, height: 138, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "running-away-balloon",
    name: "Running Away Balloon",
    src: "/memes/running-away-balloon.jpg",
    width: 761,
    height: 1024,
    textFields: [
      { id: "balloon", label: "Balloon Text", x: 464, y: 31, width: 221, height: 276, fontSize: 23, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "person", label: "Person Text", x: 38, y: 102, width: 244, height: 287, fontSize: 20, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "girlfriend", label: "Girlfriend Text", x: 23, y: 614, width: 228, height: 266, fontSize: 20, color: "#000000", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "roll-safe",
    name: "Roll Safe",
    src: "/memes/roll-safe.jpg",
    width: 702,
    height: 395,
    textFields: [
      { id: "top", label: "Top Text", x: 35, y: 10, width: 632, height: 99, fontSize: 37, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "bottom", label: "Bottom Text", x: 35, y: 286, width: 632, height: 99, fontSize: 37, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "disaster-girl",
    name: "Disaster Girl",
    src: "/memes/disaster-girl.jpg",
    width: 500,
    height: 375,
    textFields: [
      { id: "top", label: "Top Text", x: 25, y: 19, width: 450, height: 75, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "bottom", label: "Bottom Text", x: 25, y: 309, width: 450, height: 56, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "batman-slapping-robin",
    name: "Batman Slapping Robin",
    src: "/memes/batman-slapping-robin.jpg",
    width: 400,
    height: 387,
    textFields: [
      { id: "robin_speech", label: "Robin's Text", x: 16, y: 8, width: 140, height: 93, fontSize: 12, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "batman_speech", label: "Batman's Text", x: 224, y: 8, width: 140, height: 93, fontSize: 12, color: "#000000", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "gru-plan",
    name: "Gru's Plan",
    src: "/memes/gru-plan.jpg",
    width: 700,
    height: 449,
    textFields: [
      { id: "panel1", label: "Step 1", x: 168, y: 18, width: 168, height: 180, fontSize: 19, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "panel2", label: "Step 2", x: 518, y: 18, width: 168, height: 180, fontSize: 19, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "panel3", label: "Step 3", x: 168, y: 242, width: 168, height: 180, fontSize: 19, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "panel4", label: "Step 4 (Realization)", x: 518, y: 242, width: 168, height: 180, fontSize: 19, color: "#000000", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "surprised-pikachu",
    name: "Surprised Pikachu",
    src: "/memes/surprised-pikachu.jpg",
    width: 1893,
    height: 1892,
    textFields: [
      { id: "top", label: "Top Text", x: 95, y: 47, width: 1704, height: 473, fontSize: 101, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "bottom", label: "Bottom Text", x: 95, y: 1372, width: 1704, height: 473, fontSize: 101, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "ancient-aliens",
    name: "Ancient Aliens",
    src: "/memes/ancient-aliens.jpg",
    width: 500,
    height: 436,
    textFields: [
      { id: "bottom", label: "Bottom Text", x: 25, y: 316, width: 450, height: 109, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "mocking-spongebob",
    name: "Mocking SpongeBob",
    src: "/memes/mocking-spongebob.jpg",
    width: 502,
    height: 353,
    textFields: [
      { id: "top", label: "Top Text", x: 25, y: 9, width: 452, height: 88, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "bottom", label: "Bottom Text", x: 25, y: 256, width: 452, height: 88, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "boardroom-meeting",
    name: "Boardroom Meeting",
    src: "/memes/boardroom-meeting.jpg",
    width: 500,
    height: 649,
    textFields: [
      { id: "boss_speech", label: "Boss Speech", x: 120, y: 0, width: 250, height: 97, fontSize: 13, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "employee1_response", label: "Employee 1 Response", x: 5, y: 227, width: 105, height: 71, fontSize: 12, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "employee2_response", label: "Employee 2 Response", x: 150, y: 221, width: 100, height: 71, fontSize: 12, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "employee3_response", label: "Employee 3 Response", x: 285, y: 195, width: 150, height: 117, fontSize: 12, color: "#000000", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "blank-nut-button",
    name: "Blank Nut Button",
    src: "/memes/blank-nut-button.jpg",
    width: 600,
    height: 446,
    textFields: [
      { id: "button", label: "Button Text", x: 45, y: 167, width: 210, height: 112, fontSize: 16, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "waiting-skeleton",
    name: "Waiting Skeleton",
    src: "/memes/waiting-skeleton.jpg",
    width: 298,
    height: 403,
    textFields: [
      { id: "top", label: "Top Text", x: 15, y: 20, width: 268, height: 81, fontSize: 16, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "bottom", label: "Bottom Text", x: 15, y: 302, width: 268, height: 81, fontSize: 16, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "epic-handshake",
    name: "Epic Handshake",
    src: "/memes/epic-handshake.jpg",
    width: 900,
    height: 645,
    textFields: [
      { id: "left_arm", label: "Left Person/Group", x: 68, y: 145, width: 315, height: 161, fontSize: 36, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "right_arm", label: "Right Person/Group", x: 518, y: 145, width: 315, height: 161, fontSize: 36, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "handshake", label: "Agreement/Common Ground", x: 270, y: 419, width: 360, height: 129, fontSize: 30, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "x-everywhere",
    name: "X, X Everywhere",
    src: "/memes/x-everywhere.jpg",
    width: 2118,
    height: 1440,
    textFields: [
      { id: "top", label: "Top Text", x: 106, y: 72, width: 1906, height: 288, fontSize: 127, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "bottom", label: "Bottom Text", x: 106, y: 1123, width: 1906, height: 288, fontSize: 127, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "this-is-fine",
    name: "This Is Fine",
    src: "/memes/this-is-fine.jpg",
    width: 580,
    height: 282,
    textFields: [
      { id: "panel1", label: "Panel 1 Text", x: 15, y: 204, width: 261, height: 71, fontSize: 15, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "panel2", label: "Panel 2 Text", x: 305, y: 204, width: 261, height: 71, fontSize: 15, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "uno-draw-25",
    name: "UNO Draw 25",
    src: "/memes/uno-draw-25.jpg",
    width: 500,
    height: 494,
    textFields: [
      { id: "card_text", label: "UNO Card Text", x: 48, y: 64, width: 125, height: 148, fontSize: 12, color: "#000000", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "bike-fall",
    name: "Bike Fall",
    src: "/memes/bike-fall.jpg",
    width: 500,
    height: 680,
    textFields: [
      { id: "panel1", label: "Panel 1 (riding bike)", x: 263, y: 17, width: 225, height: 170, fontSize: 17, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "panel2", label: "Panel 2 (putting stick in wheel)", x: 263, y: 241, width: 225, height: 170, fontSize: 17, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "panel3", label: "Panel 3 (fallen down)", x: 263, y: 493, width: 225, height: 170, fontSize: 17, color: "#000000", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "hide-the-pain-harold",
    name: "Hide the Pain Harold",
    src: "/memes/hide-the-pain-harold.jpg",
    width: 480,
    height: 601,
    textFields: [
      { id: "top_panel", label: "Top Panel Text", x: 24, y: 6, width: 432, height: 108, fontSize: 22, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "bottom_panel", label: "Bottom Panel Text", x: 24, y: 487, width: 432, height: 108, fontSize: 22, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "doge",
    name: "Doge",
    src: "/memes/doge.jpg",
    width: 620,
    height: 620,
    textFields: [
      { id: "top_left", label: "Top Left Text", x: 31, y: 62, width: 248, height: 186, fontSize: 19, color: "#FF6600", outline: false, align: "center", valign: "middle" },
      { id: "top_right", label: "Top Right Text", x: 341, y: 62, width: 248, height: 186, fontSize: 19, color: "#FF6600", outline: false, align: "center", valign: "middle" },
      { id: "bottom_left", label: "Bottom Left Text", x: 31, y: 372, width: 248, height: 186, fontSize: 19, color: "#FF6600", outline: false, align: "center", valign: "middle" },
      { id: "bottom_right", label: "Bottom Right Text", x: 341, y: 372, width: 248, height: 186, fontSize: 19, color: "#FF6600", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "cheems",
    name: "Buff Doge vs Cheems",
    src: "/memes/cheems.png",
    width: 937,
    height: 720,
    textFields: [
      { id: "left", label: "Buff Doge Text", x: 23, y: 522, width: 422, height: 180, fontSize: 37, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "right", label: "Cheems Text", x: 492, y: 522, width: 422, height: 180, fontSize: 37, color: "#000000", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "always-has-been",
    name: "Always Has Been",
    src: "/memes/always-has-been.png",
    width: 960,
    height: 540,
    textFields: [
      { id: "question", label: "Question Text", x: 134, y: 97, width: 250, height: 97, fontSize: 38, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "answer", label: "Answer Text", x: 662, y: 351, width: 211, height: 92, fontSize: 38, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
];
