/**
 * Originally generated by scripts/generate-meme-templates.ts from Claude
 * vision API output (lib/memes/template-zones.json), then hand-corrected
 * against the debug overlay (?memeDebug=1) where the vision draft missed.
 * Do NOT regenerate this file from the script — that would overwrite the
 * corrections. Vision output is a draft; only hand-verified regions belong
 * here. New templates: run the generator, then verify with the debug
 * overlay before merging.
 *
 * x/y/width/height are fractions (0-1) of the template's width/height,
 * not absolute pixels — this way regions survive if the source image is
 * ever swapped for a different resolution.
 */
import type { MemeTemplate } from "@/lib/memes/types";

export const memeTemplates: MemeTemplate[] = [
  {
    id: "drake",
    name: "Drake Hotline Bling",
    src: "/memes/drake.jpg",
    width: 1200,
    height: 1200,
    textFields: [
      { id: "top", label: "Drake No", x: 0.54, y: 0.04, width: 0.42, height: 0.42, fontSize: 48, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "bottom", label: "Drake Yes", x: 0.54, y: 0.54, width: 0.42, height: 0.42, fontSize: 48, color: "#000000", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "distracted-boyfriend",
    name: "Distracted Boyfriend",
    src: "/memes/distracted-boyfriend.jpg",
    width: 1200,
    height: 800,
    textFields: [
      { id: "woman_red", label: "Woman in Red", x: 0.03, y: 0.58, width: 0.28, height: 0.24, fontSize: 48, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "distracted_man", label: "Distracted Boyfriend", x: 0.42, y: 0.46, width: 0.21, height: 0.36, fontSize: 48, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "girlfriend", label: "Disapproving Girlfriend", x: 0.71, y: 0.49, width: 0.23, height: 0.34, fontSize: 48, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "two-buttons",
    name: "Two Buttons",
    src: "/memes/two-buttons.jpg",
    width: 600,
    height: 908,
    textFields: [
      { id: "button1", label: "Left Button", x: 0.07, y: 0.0496, width: 0.34, height: 0.2996, fontSize: 16, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "button2", label: "Right Button", x: 0.43, y: 0.0396, width: 0.34, height: 0.2996, fontSize: 16, color: "#000000", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "change-my-mind",
    name: "Change My Mind",
    src: "/memes/change-my-mind.jpg",
    width: 482,
    height: 361,
    textFields: [
      { id: "sign", label: "Sign Text", x: 0.5, y: 0.6, width: 0.38, height: 0.21, fontSize: 19, color: "#000000", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "expanding-brain",
    name: "Expanding Brain",
    src: "/memes/expanding-brain.jpg",
    width: 857,
    height: 1202,
    textFields: [
      { id: "panel1", label: "First Panel Text", x: 0.0245, y: 0.02, width: 0.3501, height: 0.1997, fontSize: 26, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "panel2", label: "Second Panel Text", x: 0.0245, y: 0.2704, width: 0.3501, height: 0.1997, fontSize: 26, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "panel3", label: "Third Panel Text", x: 0.0245, y: 0.52, width: 0.3501, height: 0.1997, fontSize: 26, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "panel4", label: "Fourth Panel Text", x: 0.0245, y: 0.7704, width: 0.3501, height: 0.1997, fontSize: 26, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "woman-yelling-cat",
    name: "Woman Yelling at Cat",
    src: "/memes/woman-yelling-cat.jpg",
    width: 680,
    height: 438,
    textFields: [
      { id: "left", label: "Woman Yelling Text", x: 0.0206, y: 0.0091, width: 0.4603, height: 0.2192, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "right", label: "Cat Text", x: 0.5206, y: 0.0091, width: 0.4603, height: 0.2192, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "one-does-not-simply",
    name: "One Does Not Simply",
    src: "/memes/one-does-not-simply.jpg",
    width: 568,
    height: 335,
    textFields: [
      { id: "top", label: "Top Text", x: 0.0493, y: 0.0507, width: 0.8996, height: 0.2, fontSize: 30, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "bottom", label: "Bottom Text", x: 0.0493, y: 0.7493, width: 0.8996, height: 0.2, fontSize: 30, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "success-kid",
    name: "Success Kid",
    src: "/memes/success-kid.jpg",
    width: 500,
    height: 500,
    textFields: [
      { id: "top", label: "Top Text", x: 0.05, y: 0.026, width: 0.9, height: 0.25, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "bottom", label: "Bottom Text", x: 0.05, y: 0.726, width: 0.9, height: 0.25, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "is-this-a-pigeon",
    name: "Is This a Pigeon?",
    src: "/memes/is-this-a-pigeon.jpg",
    width: 1587,
    height: 1425,
    textFields: [
      { id: "butterfly", label: "Butterfly (Thing Being Questioned)", x: 0.7599, y: 0.0604, width: 0.1997, height: 0.1804, fontSize: 42, color: "#000000", outline: true, align: "center", valign: "middle" },
      { id: "person", label: "Person (The Confused One)", x: 0.0397, y: 0.7298, width: 0.3302, height: 0.16, fontSize: 42, color: "#000000", outline: true, align: "center", valign: "middle" },
      { id: "question", label: "Question Text", x: 0.39, y: 0.3004, width: 0.2602, height: 0.1404, fontSize: 48, color: "#000000", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "left-exit-12-off-ramp",
    name: "Left Exit 12 Off Ramp",
    src: "/memes/left-exit-12-off-ramp.jpg",
    width: 804,
    height: 767,
    textFields: [
      { id: "highway_sign", label: "Highway Sign Text", x: 0.2002, y: 0.09, width: 0.5796, height: 0.2399, fontSize: 32, color: "#FFFFFF", outline: false, align: "center", valign: "middle" },
      { id: "exit_ramp", label: "Exit Ramp Choice", x: 0.6306, y: 0.5502, width: 0.2699, height: 0.1799, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "straight_path", label: "Straight Path Choice", x: 0.0498, y: 0.5606, width: 0.2998, height: 0.1799, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "running-away-balloon",
    name: "Running Away Balloon",
    src: "/memes/running-away-balloon.jpg",
    width: 761,
    height: 1024,
    textFields: [
      { id: "balloon", label: "Balloon Text", x: 0.6097, y: 0.0303, width: 0.2904, height: 0.2695, fontSize: 23, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "person", label: "Person Text", x: 0.0499, y: 0.0996, width: 0.3206, height: 0.2803, fontSize: 20, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "girlfriend", label: "Girlfriend Text", x: 0.0302, y: 0.5996, width: 0.2996, height: 0.2598, fontSize: 20, color: "#000000", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "roll-safe",
    name: "Roll Safe",
    src: "/memes/roll-safe.jpg",
    width: 702,
    height: 395,
    textFields: [
      { id: "top", label: "Top Text", x: 0.0499, y: 0.0253, width: 0.9003, height: 0.2506, fontSize: 37, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "bottom", label: "Bottom Text", x: 0.0499, y: 0.7241, width: 0.9003, height: 0.2506, fontSize: 37, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "disaster-girl",
    name: "Disaster Girl",
    src: "/memes/disaster-girl.jpg",
    width: 500,
    height: 375,
    textFields: [
      { id: "top", label: "Top Text", x: 0.05, y: 0.0507, width: 0.9, height: 0.2, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "bottom", label: "Bottom Text", x: 0.05, y: 0.824, width: 0.9, height: 0.1493, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "batman-slapping-robin",
    name: "Batman Slapping Robin",
    src: "/memes/batman-slapping-robin.jpg",
    width: 400,
    height: 387,
    textFields: [
      { id: "robin_speech", label: "Robin's Text", x: 0.04, y: 0.0207, width: 0.35, height: 0.2403, fontSize: 12, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "batman_speech", label: "Batman's Text", x: 0.56, y: 0.0207, width: 0.35, height: 0.2403, fontSize: 12, color: "#000000", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "gru-plan",
    name: "Gru's Plan",
    src: "/memes/gru-plan.jpg",
    width: 700,
    height: 449,
    textFields: [
      { id: "panel1", label: "Step 1", x: 0.24, y: 0.0401, width: 0.24, height: 0.4009, fontSize: 19, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "panel2", label: "Step 2", x: 0.74, y: 0.0401, width: 0.24, height: 0.4009, fontSize: 19, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "panel3", label: "Step 3", x: 0.24, y: 0.539, width: 0.24, height: 0.4009, fontSize: 19, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "panel4", label: "Step 4 (Realization)", x: 0.74, y: 0.539, width: 0.24, height: 0.4009, fontSize: 19, color: "#000000", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "surprised-pikachu",
    name: "Surprised Pikachu",
    src: "/memes/surprised-pikachu.jpg",
    width: 1893,
    height: 1892,
    textFields: [
      { id: "top", label: "Top Text", x: 0.0502, y: 0.0248, width: 0.9002, height: 0.25, fontSize: 101, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "bottom", label: "Bottom Text", x: 0.0502, y: 0.7252, width: 0.9002, height: 0.25, fontSize: 101, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "ancient-aliens",
    name: "Ancient Aliens",
    src: "/memes/ancient-aliens.jpg",
    width: 500,
    height: 436,
    textFields: [
      { id: "bottom", label: "Bottom Text", x: 0.05, y: 0.7248, width: 0.9, height: 0.25, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "mocking-spongebob",
    name: "Mocking SpongeBob",
    src: "/memes/mocking-spongebob.jpg",
    width: 502,
    height: 353,
    textFields: [
      { id: "top", label: "Top Text", x: 0.0498, y: 0.0255, width: 0.9004, height: 0.2493, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "bottom", label: "Bottom Text", x: 0.0498, y: 0.7252, width: 0.9004, height: 0.2493, fontSize: 27, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "boardroom-meeting",
    name: "Boardroom Meeting",
    src: "/memes/boardroom-meeting.jpg",
    width: 500,
    height: 649,
    textFields: [
      { id: "boss_speech", label: "Boss Speech", x: 0.48, y: 0.01, width: 0.44, height: 0.1, fontSize: 13, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "employee1_response", label: "Employee 1 Response", x: 0.01, y: 0.3498, width: 0.21, height: 0.1094, fontSize: 12, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "employee2_response", label: "Employee 2 Response", x: 0.315, y: 0.365, width: 0.185, height: 0.075, fontSize: 12, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "employee3_response", label: "Employee 3 Response", x: 0.59, y: 0.365, width: 0.31, height: 0.075, fontSize: 12, color: "#000000", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "blank-nut-button",
    name: "Blank Nut Button",
    src: "/memes/blank-nut-button.jpg",
    width: 600,
    height: 446,
    textFields: [
      { id: "button", label: "Button Text", x: 0.075, y: 0.3744, width: 0.35, height: 0.2511, fontSize: 16, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "waiting-skeleton",
    name: "Waiting Skeleton",
    src: "/memes/waiting-skeleton.jpg",
    width: 298,
    height: 403,
    textFields: [
      { id: "top", label: "Top Text", x: 0.0503, y: 0.0496, width: 0.8993, height: 0.201, fontSize: 16, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "bottom", label: "Bottom Text", x: 0.0503, y: 0.7494, width: 0.8993, height: 0.201, fontSize: 16, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "epic-handshake",
    name: "Epic Handshake",
    src: "/memes/epic-handshake.jpg",
    width: 900,
    height: 645,
    textFields: [
      { id: "left_arm", label: "Left Person/Group", x: 0.0756, y: 0.2248, width: 0.35, height: 0.2496, fontSize: 36, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "right_arm", label: "Right Person/Group", x: 0.5756, y: 0.2248, width: 0.35, height: 0.2496, fontSize: 36, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "handshake", label: "Agreement/Common Ground", x: 0.3, y: 0.6496, width: 0.4, height: 0.2, fontSize: 30, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "x-everywhere",
    name: "X, X Everywhere",
    src: "/memes/x-everywhere.jpg",
    width: 2118,
    height: 1440,
    textFields: [
      { id: "top", label: "Top Text", x: 0.05, y: 0.05, width: 0.8999, height: 0.2, fontSize: 127, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "bottom", label: "Bottom Text", x: 0.05, y: 0.7799, width: 0.8999, height: 0.2, fontSize: 127, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "this-is-fine",
    name: "This Is Fine",
    src: "/memes/this-is-fine.jpg",
    width: 580,
    height: 282,
    textFields: [
      { id: "panel1", label: "Panel 1 Text", x: 0.0259, y: 0.7234, width: 0.45, height: 0.2518, fontSize: 15, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "panel2", label: "Panel 2 Text", x: 0.5259, y: 0.7234, width: 0.45, height: 0.2518, fontSize: 15, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "uno-draw-25",
    name: "UNO Draw 25",
    src: "/memes/uno-draw-25.jpg",
    width: 500,
    height: 494,
    textFields: [
      { id: "card_text", label: "UNO Card Text", x: 0.096, y: 0.1296, width: 0.25, height: 0.2996, fontSize: 12, color: "#000000", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "bike-fall",
    name: "Bike Fall",
    src: "/memes/bike-fall.jpg",
    width: 500,
    height: 680,
    textFields: [
      { id: "panel1", label: "Panel 1 (riding bike)", x: 0.526, y: 0.025, width: 0.45, height: 0.25, fontSize: 17, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "panel2", label: "Panel 2 (putting stick in wheel)", x: 0.526, y: 0.3544, width: 0.45, height: 0.25, fontSize: 17, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "panel3", label: "Panel 3 (fallen down)", x: 0.06, y: 0.685, width: 0.88, height: 0.063, fontSize: 17, color: "#000000", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "hide-the-pain-harold",
    name: "Hide the Pain Harold",
    src: "/memes/hide-the-pain-harold.jpg",
    width: 480,
    height: 601,
    textFields: [
      { id: "top_panel", label: "Top Panel Text", x: 0.05, y: 0.01, width: 0.9, height: 0.1797, fontSize: 22, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "bottom_panel", label: "Bottom Panel Text", x: 0.05, y: 0.8103, width: 0.9, height: 0.1797, fontSize: 22, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
  {
    id: "doge",
    name: "Doge",
    src: "/memes/doge.jpg",
    width: 620,
    height: 620,
    textFields: [
      { id: "top_left", label: "Top Left Text", x: 0.05, y: 0.1, width: 0.4, height: 0.3, fontSize: 19, color: "#FF6600", outline: false, align: "center", valign: "middle" },
      { id: "top_right", label: "Top Right Text", x: 0.55, y: 0.1, width: 0.4, height: 0.3, fontSize: 19, color: "#FF6600", outline: false, align: "center", valign: "middle" },
      { id: "bottom_left", label: "Bottom Left Text", x: 0.05, y: 0.6, width: 0.4, height: 0.3, fontSize: 19, color: "#FF6600", outline: false, align: "center", valign: "middle" },
      { id: "bottom_right", label: "Bottom Right Text", x: 0.55, y: 0.6, width: 0.4, height: 0.3, fontSize: 19, color: "#FF6600", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "cheems",
    name: "Buff Doge vs Cheems",
    src: "/memes/cheems.png",
    width: 937,
    height: 720,
    textFields: [
      { id: "left", label: "Buff Doge Text", x: 0.0245, y: 0.725, width: 0.4504, height: 0.25, fontSize: 37, color: "#000000", outline: false, align: "center", valign: "middle" },
      { id: "right", label: "Cheems Text", x: 0.5251, y: 0.725, width: 0.4504, height: 0.25, fontSize: 37, color: "#000000", outline: false, align: "center", valign: "middle" },
    ],
  },
  {
    id: "always-has-been",
    name: "Always Has Been",
    src: "/memes/always-has-been.png",
    width: 960,
    height: 540,
    textFields: [
      { id: "question", label: "Question Text", x: 0.1396, y: 0.1796, width: 0.2604, height: 0.1796, fontSize: 38, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
      { id: "answer", label: "Answer Text", x: 0.6896, y: 0.65, width: 0.2198, height: 0.1704, fontSize: 38, color: "#FFFFFF", outline: true, align: "center", valign: "middle" },
    ],
  },
];
