/**
 * Auto-generated by scripts/generate-meme-templates.ts
 * Text zones detected by Claude vision API.
 * Do not edit manually — re-run the script instead.
 */
import type { MemeTemplate } from "@/lib/memes/types";

export const memeTemplates: MemeTemplate[] = [
  {
    id: "drake",
    name: "Drake Hotline Bling",
    src: "/memes/drake.jpg",
    width: 1200,
    height: 1200,
    textFields: [
      { id: "top", label: "Drake No", x: 900, y: 300, maxWidth: 540, maxHeight: 480, fontSize: 24, color: "#000000", outline: false, align: "center" },
      { id: "bottom", label: "Drake Yes", x: 900, y: 900, maxWidth: 540, maxHeight: 480, fontSize: 24, color: "#000000", outline: false, align: "center" },
    ],
  },
  {
    id: "distracted-boyfriend",
    name: "Distracted Boyfriend",
    src: "/memes/distracted-boyfriend.jpg",
    width: 1200,
    height: 800,
    textFields: [
      { id: "woman_red", label: "Woman in Red", x: 300, y: 680, maxWidth: 480, maxHeight: 160, fontSize: 24, color: "#FFFFFF", outline: true, align: "center" },
      { id: "distracted_man", label: "Distracted Boyfriend", x: 600, y: 680, maxWidth: 360, maxHeight: 160, fontSize: 24, color: "#FFFFFF", outline: true, align: "center" },
      { id: "girlfriend", label: "Disapproving Girlfriend", x: 960, y: 680, maxWidth: 420, maxHeight: 160, fontSize: 24, color: "#FFFFFF", outline: true, align: "center" },
    ],
  },
  {
    id: "two-buttons",
    name: "Two Buttons",
    src: "/memes/two-buttons.jpg",
    width: 600,
    height: 908,
    textFields: [
      { id: "button1", label: "Left Button", x: 150, y: 227, maxWidth: 210, maxHeight: 227, fontSize: 16, color: "#000000", outline: false, align: "center" },
      { id: "button2", label: "Right Button", x: 450, y: 227, maxWidth: 210, maxHeight: 227, fontSize: 16, color: "#000000", outline: false, align: "center" },
    ],
  },
  {
    id: "change-my-mind",
    name: "Change My Mind",
    src: "/memes/change-my-mind.jpg",
    width: 482,
    height: 361,
    textFields: [
      { id: "sign", label: "Sign Text", x: 241, y: 264, maxWidth: 313, maxHeight: 65, fontSize: 24, color: "#000000", outline: false, align: "center" },
    ],
  },
  {
    id: "expanding-brain",
    name: "Expanding Brain",
    src: "/memes/expanding-brain.jpg",
    width: 857,
    height: 1202,
    textFields: [
      { id: "panel1", label: "First Panel Text", x: 171, y: 144, maxWidth: 300, maxHeight: 240, fontSize: 18, color: "#FFFFFF", outline: true, align: "center" },
      { id: "panel2", label: "Second Panel Text", x: 171, y: 445, maxWidth: 300, maxHeight: 240, fontSize: 18, color: "#FFFFFF", outline: true, align: "center" },
      { id: "panel3", label: "Third Panel Text", x: 171, y: 745, maxWidth: 300, maxHeight: 240, fontSize: 18, color: "#FFFFFF", outline: true, align: "center" },
      { id: "panel4", label: "Fourth Panel Text", x: 171, y: 1046, maxWidth: 300, maxHeight: 240, fontSize: 18, color: "#FFFFFF", outline: true, align: "center" },
    ],
  },
  {
    id: "woman-yelling-cat",
    name: "Woman Yelling at Cat",
    src: "/memes/woman-yelling-cat.jpg",
    width: 680,
    height: 438,
    textFields: [
      { id: "left", label: "Woman Yelling Text", x: 170, y: 66, maxWidth: 306, maxHeight: 110, fontSize: 24, color: "#FFFFFF", outline: true, align: "center" },
      { id: "right", label: "Cat Text", x: 510, y: 66, maxWidth: 306, maxHeight: 110, fontSize: 24, color: "#FFFFFF", outline: true, align: "center" },
    ],
  },
  {
    id: "one-does-not-simply",
    name: "One Does Not Simply",
    src: "/memes/one-does-not-simply.jpg",
    width: 568,
    height: 335,
    textFields: [
      { id: "top", label: "Top Text", x: 284, y: 50, maxWidth: 511, maxHeight: 67, fontSize: 32, color: "#FFFFFF", outline: true, align: "center" },
      { id: "bottom", label: "Bottom Text", x: 284, y: 285, maxWidth: 511, maxHeight: 67, fontSize: 32, color: "#FFFFFF", outline: true, align: "center" },
    ],
  },
  {
    id: "success-kid",
    name: "Success Kid",
    src: "/memes/success-kid.jpg",
    width: 500,
    height: 500,
    textFields: [
      { id: "top", label: "Top Text", x: 250, y: 75, maxWidth: 450, maxHeight: 125, fontSize: 32, color: "#FFFFFF", outline: true, align: "center" },
      { id: "bottom", label: "Bottom Text", x: 250, y: 425, maxWidth: 450, maxHeight: 125, fontSize: 32, color: "#FFFFFF", outline: true, align: "center" },
    ],
  },
  {
    id: "is-this-a-pigeon",
    name: "Is This a Pigeon?",
    src: "/memes/is-this-a-pigeon.jpg",
    width: 1587,
    height: 1425,
    textFields: [
      { id: "butterfly", label: "Butterfly (Thing Being Questioned)", x: 1349, y: 356, maxWidth: 397, maxHeight: 285, fontSize: 16, color: "#000000", outline: true, align: "center" },
      { id: "person", label: "Person (The Confused One)", x: 397, y: 1211, maxWidth: 555, maxHeight: 214, fontSize: 16, color: "#000000", outline: true, align: "center" },
      { id: "question", label: "Question Text", x: 794, y: 1311, maxWidth: 1428, maxHeight: 171, fontSize: 18, color: "#000000", outline: true, align: "center" },
    ],
  },
  {
    id: "left-exit-12-off-ramp",
    name: "Left Exit 12 Off Ramp",
    src: "/memes/left-exit-12-off-ramp.jpg",
    width: 804,
    height: 767,
    textFields: [
      { id: "highway_sign", label: "Highway Sign Text", x: 402, y: 153, maxWidth: 482, maxHeight: 192, fontSize: 24, color: "#FFFFFF", outline: false, align: "center" },
      { id: "exit_ramp", label: "Exit Ramp Choice", x: 603, y: 499, maxWidth: 322, maxHeight: 153, fontSize: 20, color: "#000000", outline: true, align: "center" },
      { id: "straight_path", label: "Straight Path Choice", x: 201, y: 575, maxWidth: 322, maxHeight: 153, fontSize: 20, color: "#000000", outline: true, align: "center" },
    ],
  },
  {
    id: "running-away-balloon",
    name: "Running Away Balloon",
    src: "/memes/running-away-balloon.jpg",
    width: 761,
    height: 1024,
    textFields: [
      { id: "balloon", label: "Balloon Text", x: 571, y: 205, maxWidth: 266, maxHeight: 256, fontSize: 18, color: "#000000", outline: false, align: "center" },
      { id: "person", label: "Person Text", x: 190, y: 358, maxWidth: 228, maxHeight: 205, fontSize: 16, color: "#000000", outline: true, align: "center" },
      { id: "girlfriend", label: "Girlfriend Text", x: 190, y: 870, maxWidth: 228, maxHeight: 205, fontSize: 16, color: "#000000", outline: true, align: "center" },
    ],
  },
  {
    id: "roll-safe",
    name: "Roll Safe",
    src: "/memes/roll-safe.jpg",
    width: 702,
    height: 395,
    textFields: [
      { id: "top", label: "Top Text", x: 351, y: 59, maxWidth: 632, maxHeight: 99, fontSize: 32, color: "#FFFFFF", outline: true, align: "center" },
      { id: "bottom", label: "Bottom Text", x: 351, y: 336, maxWidth: 632, maxHeight: 99, fontSize: 32, color: "#FFFFFF", outline: true, align: "center" },
    ],
  },
  {
    id: "disaster-girl",
    name: "Disaster Girl",
    src: "/memes/disaster-girl.jpg",
    width: 500,
    height: 375,
    textFields: [
      { id: "top", label: "Top Text", x: 250, y: 56, maxWidth: 450, maxHeight: 75, fontSize: 32, color: "#FFFFFF", outline: true, align: "center" },
      { id: "bottom", label: "Bottom Text", x: 250, y: 338, maxWidth: 450, maxHeight: 56, fontSize: 32, color: "#FFFFFF", outline: true, align: "center" },
    ],
  },
  {
    id: "batman-slapping-robin",
    name: "Batman Slapping Robin",
    src: "/memes/batman-slapping-robin.jpg",
    width: 400,
    height: 387,
    textFields: [
      { id: "robin_speech", label: "Robin's Text", x: 100, y: 58, maxWidth: 180, maxHeight: 97, fontSize: 16, color: "#000000", outline: true, align: "center" },
      { id: "batman_speech", label: "Batman's Text", x: 300, y: 58, maxWidth: 180, maxHeight: 97, fontSize: 16, color: "#000000", outline: true, align: "center" },
    ],
  },
  {
    id: "gru-plan",
    name: "Gru's Plan",
    src: "/memes/gru-plan.jpg",
    width: 700,
    height: 449,
    textFields: [
      { id: "panel1", label: "Step 1", x: 266, y: 103, maxWidth: 154, maxHeight: 171, fontSize: 16, color: "#000000", outline: false, align: "center" },
      { id: "panel2", label: "Step 2", x: 616, y: 103, maxWidth: 154, maxHeight: 171, fontSize: 16, color: "#000000", outline: false, align: "center" },
      { id: "panel3", label: "Step 3", x: 266, y: 328, maxWidth: 154, maxHeight: 171, fontSize: 16, color: "#000000", outline: false, align: "center" },
      { id: "panel4", label: "Step 4 (Realization)", x: 616, y: 328, maxWidth: 154, maxHeight: 171, fontSize: 16, color: "#000000", outline: false, align: "center" },
    ],
  },
  {
    id: "surprised-pikachu",
    name: "Surprised Pikachu",
    src: "/memes/surprised-pikachu.jpg",
    width: 1893,
    height: 1892,
    textFields: [
      { id: "top", label: "Top Text", x: 947, y: 284, maxWidth: 1704, maxHeight: 473, fontSize: 32, color: "#FFFFFF", outline: true, align: "center" },
      { id: "bottom", label: "Bottom Text", x: 947, y: 1608, maxWidth: 1704, maxHeight: 473, fontSize: 32, color: "#FFFFFF", outline: true, align: "center" },
    ],
  },
  {
    id: "ancient-aliens",
    name: "Ancient Aliens",
    src: "/memes/ancient-aliens.jpg",
    width: 500,
    height: 436,
    textFields: [
      { id: "bottom", label: "Bottom Text", x: 250, y: 371, maxWidth: 450, maxHeight: 109, fontSize: 32, color: "#FFFFFF", outline: true, align: "center" },
    ],
  },
  {
    id: "mocking-spongebob",
    name: "Mocking SpongeBob",
    src: "/memes/mocking-spongebob.jpg",
    width: 502,
    height: 353,
    textFields: [
      { id: "top", label: "Top Text", x: 251, y: 53, maxWidth: 452, maxHeight: 88, fontSize: 32, color: "#FFFFFF", outline: true, align: "center" },
      { id: "bottom", label: "Bottom Text", x: 251, y: 300, maxWidth: 452, maxHeight: 88, fontSize: 32, color: "#FFFFFF", outline: true, align: "center" },
    ],
  },
  {
    id: "boardroom-meeting",
    name: "Boardroom Meeting",
    src: "/memes/boardroom-meeting.jpg",
    width: 500,
    height: 649,
    textFields: [
      { id: "boss_speech", label: "Boss Speech", x: 325, y: 78, maxWidth: 300, maxHeight: 97, fontSize: 16, color: "#000000", outline: false, align: "center" },
      { id: "employee1_response", label: "Employee 1 Response", x: 100, y: 370, maxWidth: 125, maxHeight: 78, fontSize: 14, color: "#000000", outline: false, align: "center" },
      { id: "employee2_response", label: "Employee 2 Response", x: 250, y: 370, maxWidth: 125, maxHeight: 78, fontSize: 14, color: "#000000", outline: false, align: "center" },
      { id: "employee3_response", label: "Employee 3 Response", x: 400, y: 370, maxWidth: 175, maxHeight: 78, fontSize: 14, color: "#000000", outline: false, align: "center" },
    ],
  },
  {
    id: "blank-nut-button",
    name: "Blank Nut Button",
    src: "/memes/blank-nut-button.jpg",
    width: 600,
    height: 446,
    textFields: [
      { id: "button", label: "Button Text", x: 150, y: 223, maxWidth: 210, maxHeight: 112, fontSize: 16, color: "#FFFFFF", outline: true, align: "center" },
    ],
  },
  {
    id: "waiting-skeleton",
    name: "Waiting Skeleton",
    src: "/memes/waiting-skeleton.jpg",
    width: 298,
    height: 403,
    textFields: [
      { id: "top", label: "Top Text", x: 149, y: 60, maxWidth: 268, maxHeight: 81, fontSize: 32, color: "#FFFFFF", outline: true, align: "center" },
      { id: "bottom", label: "Bottom Text", x: 149, y: 343, maxWidth: 268, maxHeight: 81, fontSize: 32, color: "#FFFFFF", outline: true, align: "center" },
    ],
  },
  {
    id: "epic-handshake",
    name: "Epic Handshake",
    src: "/memes/epic-handshake.jpg",
    width: 900,
    height: 645,
    textFields: [
      { id: "left_arm", label: "Left Person/Group", x: 225, y: 226, maxWidth: 315, maxHeight: 161, fontSize: 24, color: "#FFFFFF", outline: true, align: "center" },
      { id: "right_arm", label: "Right Person/Group", x: 675, y: 226, maxWidth: 315, maxHeight: 161, fontSize: 24, color: "#FFFFFF", outline: true, align: "center" },
      { id: "handshake", label: "Agreement/Common Ground", x: 450, y: 484, maxWidth: 360, maxHeight: 129, fontSize: 20, color: "#FFFFFF", outline: true, align: "center" },
    ],
  },
  {
    id: "x-everywhere",
    name: "X, X Everywhere",
    src: "/memes/x-everywhere.jpg",
    width: 2118,
    height: 1440,
    textFields: [
      { id: "top", label: "Top Text", x: 1059, y: 216, maxWidth: 1906, maxHeight: 288, fontSize: 36, color: "#FFFFFF", outline: true, align: "center" },
      { id: "bottom", label: "Bottom Text", x: 1059, y: 1267, maxWidth: 1906, maxHeight: 288, fontSize: 36, color: "#FFFFFF", outline: true, align: "center" },
    ],
  },
  {
    id: "this-is-fine",
    name: "This Is Fine",
    src: "/memes/this-is-fine.jpg",
    width: 580,
    height: 282,
    textFields: [
      { id: "panel1", label: "Panel 1 Text", x: 145, y: 240, maxWidth: 261, maxHeight: 71, fontSize: 16, color: "#FFFFFF", outline: true, align: "center" },
      { id: "panel2", label: "Panel 2 Text", x: 435, y: 240, maxWidth: 261, maxHeight: 71, fontSize: 16, color: "#FFFFFF", outline: true, align: "center" },
    ],
  },
  {
    id: "uno-draw-25",
    name: "UNO Draw 25",
    src: "/memes/uno-draw-25.jpg",
    width: 500,
    height: 494,
    textFields: [
      { id: "card_text", label: "UNO Card Text", x: 110, y: 138, maxWidth: 125, maxHeight: 148, fontSize: 14, color: "#000000", outline: false, align: "center" },
    ],
  },
  {
    id: "bike-fall",
    name: "Bike Fall",
    src: "/memes/bike-fall.jpg",
    width: 500,
    height: 680,
    textFields: [
      { id: "panel1", label: "Panel 1 (riding bike)", x: 375, y: 102, maxWidth: 225, maxHeight: 170, fontSize: 20, color: "#000000", outline: false, align: "center" },
      { id: "panel2", label: "Panel 2 (putting stick in wheel)", x: 375, y: 326, maxWidth: 225, maxHeight: 170, fontSize: 20, color: "#000000", outline: false, align: "center" },
      { id: "panel3", label: "Panel 3 (fallen down)", x: 375, y: 578, maxWidth: 225, maxHeight: 170, fontSize: 20, color: "#000000", outline: false, align: "center" },
    ],
  },
  {
    id: "hide-the-pain-harold",
    name: "Hide the Pain Harold",
    src: "/memes/hide-the-pain-harold.jpg",
    width: 480,
    height: 601,
    textFields: [
      { id: "top_panel", label: "Top Panel Text", x: 240, y: 60, maxWidth: 432, maxHeight: 108, fontSize: 28, color: "#FFFFFF", outline: true, align: "center" },
      { id: "bottom_panel", label: "Bottom Panel Text", x: 240, y: 541, maxWidth: 432, maxHeight: 108, fontSize: 28, color: "#FFFFFF", outline: true, align: "center" },
    ],
  },
  {
    id: "doge",
    name: "Doge",
    src: "/memes/doge.jpg",
    width: 620,
    height: 620,
    textFields: [
      { id: "top_left", label: "Top Left Text", x: 155, y: 155, maxWidth: 248, maxHeight: 186, fontSize: 18, color: "#FF6600", outline: false, align: "center" },
      { id: "top_right", label: "Top Right Text", x: 465, y: 155, maxWidth: 248, maxHeight: 186, fontSize: 18, color: "#FF6600", outline: false, align: "center" },
      { id: "bottom_left", label: "Bottom Left Text", x: 155, y: 465, maxWidth: 248, maxHeight: 186, fontSize: 18, color: "#FF6600", outline: false, align: "center" },
      { id: "bottom_right", label: "Bottom Right Text", x: 465, y: 465, maxWidth: 248, maxHeight: 186, fontSize: 18, color: "#FF6600", outline: false, align: "center" },
    ],
  },
  {
    id: "cheems",
    name: "Buff Doge vs Cheems",
    src: "/memes/cheems.png",
    width: 937,
    height: 720,
    textFields: [
      { id: "left", label: "Buff Doge Text", x: 234, y: 612, maxWidth: 422, maxHeight: 180, fontSize: 24, color: "#000000", outline: false, align: "center" },
      { id: "right", label: "Cheems Text", x: 703, y: 612, maxWidth: 422, maxHeight: 180, fontSize: 24, color: "#000000", outline: false, align: "center" },
    ],
  },
  {
    id: "always-has-been",
    name: "Always Has Been",
    src: "/memes/always-has-been.png",
    width: 960,
    height: 540,
    textFields: [
      { id: "question", label: "Question Text", x: 240, y: 162, maxWidth: 384, maxHeight: 135, fontSize: 24, color: "#FFFFFF", outline: true, align: "center" },
      { id: "answer", label: "Answer Text", x: 720, y: 432, maxWidth: 384, maxHeight: 135, fontSize: 24, color: "#FFFFFF", outline: true, align: "center" },
    ],
  },
];
