// ─── Static word lists and quotes for the Typing Test ────────────────────────

export const english200 = [
  "the", "be", "to", "of", "and", "a", "in", "that", "have", "it",
  "for", "not", "on", "with", "he", "as", "you", "do", "at", "this",
  "but", "his", "by", "from", "they", "we", "her", "she", "or", "an",
  "will", "my", "one", "all", "would", "there", "their", "what", "so", "up",
  "out", "if", "about", "who", "get", "which", "go", "me", "when", "make",
  "can", "like", "time", "no", "just", "him", "know", "take", "people", "into",
  "year", "your", "good", "some", "could", "them", "see", "other", "than", "then",
  "now", "look", "only", "come", "its", "over", "think", "also", "back", "after",
  "use", "two", "how", "our", "work", "first", "well", "way", "even", "new",
  "want", "because", "any", "these", "give", "day", "most", "us", "between", "need",
  "large", "often", "hand", "high", "place", "hold", "turn", "move", "live", "believe",
  "bring", "happen", "write", "provide", "sit", "stand", "lose", "pay", "meet", "include",
  "continue", "set", "learn", "change", "lead", "understand", "watch", "follow", "stop", "create",
  "speak", "read", "spend", "grow", "open", "walk", "win", "offer", "remember", "love",
  "consider", "appear", "buy", "wait", "serve", "die", "send", "expect", "build", "stay",
  "fall", "cut", "reach", "kill", "remain", "suggest", "raise", "pass", "sell", "require",
  "report", "decide", "pull", "break", "run", "tell", "ask", "show", "feel", "try",
  "call", "keep", "let", "begin", "seem", "help", "talk", "start", "might", "hear",
  "play", "point", "part", "put", "found", "head", "still", "long", "own", "say",
  "each", "much", "both", "old", "end", "does", "while", "must", "home", "life",
];

export const english1000 = [
  // Common verbs
  "the", "be", "to", "of", "and", "a", "in", "that", "have", "it",
  "for", "not", "on", "with", "he", "as", "you", "do", "at", "this",
  "but", "his", "by", "from", "they", "we", "her", "she", "or", "an",
  "will", "my", "one", "all", "would", "there", "their", "what", "so", "up",
  "out", "if", "about", "who", "get", "which", "go", "me", "when", "make",
  "can", "like", "time", "no", "just", "him", "know", "take", "people", "into",
  "year", "your", "good", "some", "could", "them", "see", "other", "than", "then",
  "now", "look", "only", "come", "its", "over", "think", "also", "back", "after",
  "use", "two", "how", "our", "work", "first", "well", "way", "even", "new",
  "want", "because", "any", "these", "give", "day", "most", "us", "between", "need",
  // More common words
  "large", "often", "hand", "high", "place", "hold", "turn", "move", "live", "believe",
  "bring", "happen", "write", "provide", "sit", "stand", "lose", "pay", "meet", "include",
  "continue", "set", "learn", "change", "lead", "understand", "watch", "follow", "stop", "create",
  "speak", "read", "spend", "grow", "open", "walk", "win", "offer", "remember", "love",
  "consider", "appear", "buy", "wait", "serve", "die", "send", "expect", "build", "stay",
  "fall", "cut", "reach", "kill", "remain", "suggest", "raise", "pass", "sell", "require",
  "report", "decide", "pull", "break", "run", "tell", "ask", "show", "feel", "try",
  "call", "keep", "let", "begin", "seem", "help", "talk", "start", "might", "hear",
  "play", "point", "part", "put", "found", "head", "still", "long", "own", "say",
  "each", "much", "both", "old", "end", "does", "while", "must", "home", "life",
  // Extended vocabulary — nouns
  "world", "school", "state", "family", "student", "group", "country", "problem", "story",
  "company", "system", "program", "question", "government", "number", "night", "water",
  "room", "mother", "area", "money", "book", "example", "city", "game", "food", "body",
  "door", "health", "history", "morning", "girl", "boy", "friend", "father", "power",
  "hour", "music", "person", "party", "result", "reason", "name", "idea", "market",
  "center", "table", "office", "river", "road", "car", "house", "church", "community",
  "south", "north", "college", "court", "ground", "job", "board", "picture", "plan",
  "effect", "field", "class", "police", "thought", "business", "woman", "interest",
  "process", "team", "practice", "figure", "training", "sense", "mind", "step", "voice",
  "machine", "light", "level", "paper", "model", "experience", "future", "moment",
  "computer", "season", "society", "nature", "street", "store", "garden", "service",
  "window", "view", "product", "surface", "ocean", "island", "mountain", "weather",
  "village", "forest", "animal", "summer", "winter", "spring", "color", "flower",
  "language", "kitchen", "earth", "letter", "brother", "sister", "daughter", "husband",
  "doctor", "teacher", "movie", "music", "energy", "coffee", "lunch", "dinner",
  "camera", "phone", "bridge", "corner", "library", "station", "airport", "engine",
  "minute", "second", "dream", "heart", "memory", "brain", "spirit", "attention",
  "safety", "choice", "detail", "signal", "pattern", "message", "project", "bridge",
  // Extended vocabulary — verbs
  "accept", "achieve", "add", "admit", "affect", "agree", "allow", "answer", "apply",
  "arrive", "assume", "attack", "avoid", "beat", "belong", "borrow", "breathe", "burn",
  "celebrate", "challenge", "chase", "check", "choose", "claim", "climb", "close", "collect",
  "compare", "compete", "complain", "complete", "confirm", "connect", "contain", "control",
  "cook", "copy", "correct", "count", "cover", "cross", "dance", "deal", "deliver",
  "demand", "deny", "depend", "describe", "design", "destroy", "develop", "discover",
  "discuss", "divide", "doubt", "draw", "dress", "drink", "drive", "drop", "earn",
  "eat", "employ", "encourage", "enjoy", "enter", "escape", "examine", "exchange",
  "exist", "expand", "explain", "explore", "express", "extend", "face", "fail",
  "feed", "fight", "fill", "finish", "fit", "fix", "fly", "force", "forget",
  "form", "gain", "gather", "grab", "guess", "handle", "hang", "hate", "hit",
  "hope", "hurt", "identify", "ignore", "imagine", "improve", "increase", "influence",
  "inform", "insist", "intend", "introduce", "invite", "involve", "join", "judge",
  "jump", "kick", "knock", "lack", "laugh", "launch", "lay", "lift", "limit",
  "link", "listen", "lock", "manage", "mark", "match", "matter", "measure", "mention",
  "mind", "miss", "mix", "mount", "notice", "obtain", "occur", "operate", "order",
  "organize", "overcome", "owe", "own", "participate", "perform", "permit", "pick",
  "plant", "pour", "prefer", "prepare", "present", "press", "prevent", "produce",
  "promise", "protect", "prove", "publish", "push", "quit", "rain", "react", "receive",
  "recognize", "recommend", "recover", "reduce", "reflect", "refuse", "relate", "release",
  "rely", "remove", "repeat", "replace", "reply", "represent", "request", "research",
  "resolve", "respond", "rest", "result", "retire", "reveal", "ring", "rise", "roll",
  "rush", "satisfy", "save", "search", "shake", "shape", "share", "shift", "shoot",
  "shop", "shut", "sign", "sing", "sleep", "slide", "smile", "smoke", "solve",
  "sort", "spread", "steal", "stick", "strike", "struggle", "study", "succeed",
  "suffer", "supply", "support", "suppose", "survive", "suspect", "swim", "swing",
  "switch", "teach", "tear", "tend", "test", "thank", "throw", "tie", "touch",
  "track", "trade", "train", "travel", "treat", "trust", "wonder", "worry", "wrap",
  // Extended vocabulary — adjectives
  "able", "afraid", "angry", "available", "aware", "basic", "beautiful", "best",
  "better", "big", "black", "blue", "bright", "brown", "busy", "calm", "careful",
  "certain", "cheap", "clean", "clear", "close", "cold", "common", "complete",
  "complex", "cool", "critical", "cultural", "current", "dangerous", "dark", "dead",
  "deep", "democratic", "different", "difficult", "dry", "early", "east", "easy",
  "economic", "effective", "entire", "environmental", "equal", "every", "exact",
  "fair", "false", "familiar", "famous", "far", "fast", "fat", "federal", "final",
  "financial", "fine", "flat", "foreign", "formal", "former", "forward", "free",
  "fresh", "front", "full", "funny", "general", "global", "golden", "grand",
  "great", "green", "guilty", "happy", "hard", "heavy", "hot", "huge", "human",
  "important", "impossible", "independent", "individual", "industrial", "initial",
  "inner", "joint", "key", "kind", "known", "late", "left", "legal", "likely",
  "little", "living", "local", "lost", "low", "lucky", "main", "major", "male",
  "massive", "medical", "mental", "middle", "military", "minor", "modern", "moral",
  "narrow", "national", "natural", "near", "necessary", "negative", "normal", "nuclear",
  "obvious", "odd", "official", "opposite", "ordinary", "original", "overall", "pale",
  "perfect", "physical", "plain", "pleasant", "plus", "political", "poor", "popular",
  "positive", "possible", "powerful", "previous", "primary", "private", "proper",
  "proud", "public", "pure", "quick", "quiet", "rare", "raw", "ready", "real",
  "recent", "red", "regular", "relevant", "responsible", "rich", "right", "rough",
  "round", "royal", "rural", "safe", "secret", "senior", "serious", "severe",
  "sharp", "short", "sick", "significant", "silent", "silly", "similar", "simple",
  "single", "slight", "slow", "small", "smart", "smooth", "social", "soft", "solid",
  "sorry", "southern", "special", "stable", "standard", "strange", "strict", "strong",
  "stupid", "sudden", "suitable", "sure", "sweet", "tall", "technical", "terrible",
  "thick", "thin", "tight", "tiny", "top", "total", "tough", "traditional", "true",
  "typical", "ugly", "unable", "unique", "united", "unlikely", "upper", "useful",
  "usual", "valuable", "various", "vast", "visible", "visual", "warm", "weak",
  "wealthy", "western", "whole", "wide", "wild", "willing", "wise", "wooden",
  "worth", "wrong", "yellow", "young",
  // Common adverbs and other
  "about", "above", "across", "actually", "ago", "almost", "alone", "along",
  "already", "always", "among", "around", "away", "before", "behind", "below",
  "best", "beyond", "close", "daily", "deeply", "down", "during", "early",
  "easily", "either", "else", "enough", "especially", "ever", "every",
  "exactly", "extra", "fairly", "finally", "forward", "generally", "gently",
  "half", "hardly", "here", "however", "instead", "itself", "later",
  "least", "less", "likely", "maybe", "merely", "mostly", "myself", "nearly",
  "neither", "never", "nobody", "none", "nor", "nothing", "nowhere", "off",
  "once", "only", "otherwise", "outside", "perhaps", "please", "pretty",
  "probably", "quite", "rather", "really", "recently", "simply", "since",
  "slightly", "slowly", "somehow", "something", "sometimes", "soon", "south",
  "still", "such", "therefore", "through", "thus", "today", "together",
  "tonight", "toward", "twice", "under", "unless", "until", "upon",
  "usually", "very", "whatever", "whenever", "whether", "without", "yet",
];

export interface Quote {
  text: string;
  author: string;
}

export const quotes: Quote[] = [
  // Short quotes (1-2 sentences)
  { text: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "To be or not to be, that is the question.", author: "William Shakespeare" },
  { text: "I think, therefore I am.", author: "Rene Descartes" },
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
  { text: "Knowledge is power.", author: "Francis Bacon" },
  { text: "I came, I saw, I conquered.", author: "Julius Caesar" },
  { text: "Give me liberty, or give me death.", author: "Patrick Henry" },
  { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "Brevity is the soul of wit.", author: "William Shakespeare" },
  { text: "The pen is mightier than the sword.", author: "Edward Bulwer-Lytton" },
  { text: "Actions speak louder than words.", author: "Abraham Lincoln" },
  { text: "Early to bed and early to rise makes a man healthy, wealthy, and wise.", author: "Benjamin Franklin" },

  // Medium quotes (2-3 sentences)
  { text: "It is not the strongest of the species that survives, nor the most intelligent. It is the one that is most adaptable to change.", author: "Charles Darwin" },
  { text: "In three words I can sum up everything I have learned about life: it goes on. No matter what happens, no matter how dark the night, the sun will rise again.", author: "Robert Frost" },
  { text: "Twenty years from now you will be more disappointed by the things that you did not do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor.", author: "Mark Twain" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall. Our greatest weakness lies in giving up.", author: "Nelson Mandela" },
  { text: "You must be the change you wish to see in the world. Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
  { text: "Do not go where the path may lead. Go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { text: "It is during our darkest moments that we must focus to see the light. The only way to do great work is to love what you do.", author: "Aristotle" },
  { text: "We hold these truths to be self-evident, that all men are created equal. They are endowed by their Creator with certain unalienable rights.", author: "Thomas Jefferson" },
  { text: "If you look at what you have in life, you will always have more. If you look at what you do not have in life, you will never have enough.", author: "Oprah Winfrey" },
  { text: "The future belongs to those who believe in the beauty of their dreams. No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { text: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.", author: "Martin Luther King Jr." },
  { text: "Life is what happens when you are busy making other plans. In the end, it is not the years in your life that count. It is the life in your years.", author: "John Lennon" },
  { text: "A room without books is like a body without a soul. The only thing necessary for the triumph of evil is for good men to do nothing.", author: "Marcus Tullius Cicero" },

  // Longer quotes (3-5 sentences)
  { text: "Success is not final, failure is not fatal. It is the courage to continue that counts. If you are going through hell, keep going. We make a living by what we get, but we make a life by what we give.", author: "Winston Churchill" },
  { text: "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness. It was the epoch of belief, it was the epoch of incredulity. It was the season of light, it was the season of darkness.", author: "Charles Dickens" },
  { text: "Two roads diverged in a wood, and I took the one less traveled by, and that has made all the difference. The woods are lovely, dark, and deep, but I have promises to keep, and miles to go before I sleep.", author: "Robert Frost" },
  { text: "Whenever you find yourself on the side of the majority, it is time to reform. The secret of getting ahead is getting started. If you tell the truth, you do not have to remember anything.", author: "Mark Twain" },
  { text: "The best time to plant a tree was twenty years ago. The second best time is now. Do not wait for the perfect moment. Take the moment and make it perfect. Every accomplishment starts with the decision to try.", author: "Chinese Proverb" },
  { text: "Four score and seven years ago our fathers brought forth on this continent a new nation, conceived in liberty, and dedicated to the proposition that all men are created equal.", author: "Abraham Lincoln" },
  { text: "I have a dream that one day this nation will rise up and live out the true meaning of its creed. We hold these truths to be self-evident, that all men are created equal. I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character.", author: "Martin Luther King Jr." },
  { text: "The only limit to our realization of tomorrow will be our doubts of today. Let us move forward with strong and active faith. Happiness is not something ready made. It comes from your own actions.", author: "Franklin D. Roosevelt" },
  { text: "The whole secret of a successful life is to find out what is one's destiny to do, and then do it. To accomplish great things, we must not only act, but also dream; not only plan, but also believe.", author: "Henry Ford" },
  { text: "It does not matter how slowly you go as long as you do not stop. Life is really simple, but we insist on making it complicated. Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { text: "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world. The important thing is not to stop questioning. Curiosity has its own reason for existence.", author: "Albert Einstein" },
  { text: "All that glitters is not gold. The course of true love never did run smooth. Love all, trust a few, do wrong to none. We know what we are, but know not what we may be.", author: "William Shakespeare" },
  { text: "Do not judge each day by the harvest you reap but by the seeds that you plant. Keep your face always toward the sunshine and shadows will fall behind you. The best preparation for tomorrow is doing your best today.", author: "Ralph Waldo Emerson" },
  { text: "Yesterday is gone. Tomorrow has not yet come. We have only today. Let us begin. If you judge people, you have no time to love them. Peace begins with a smile.", author: "Mother Teresa" },
  { text: "The measure of intelligence is the ability to change. Strive not to be a success, but rather to be of value. Try not to become a man of success. Rather become a man of value.", author: "Albert Einstein" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us. To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
  { text: "A wise man can learn more from a foolish question than a fool can learn from a wise answer. The only way to have a friend is to be one. Trust thyself. Every heart vibrates to that iron string.", author: "Ralph Waldo Emerson" },

  // Extended literary and philosophical quotes
  { text: "All happy families are alike; each unhappy family is unhappy in its own way. Everything that we see is a shadow cast by that which we do not see.", author: "Leo Tolstoy" },
  { text: "The only thing that interferes with my learning is my education. Few are those who see with their own eyes and feel with their own hearts. Logic will get you from A to Z. Imagination will get you everywhere.", author: "Albert Einstein" },
  { text: "To thine own self be true, and it must follow, as the night the day, thou canst not then be false to any man. This above all: to thine own self be true.", author: "William Shakespeare" },
  { text: "Ask not what your country can do for you. Ask what you can do for your country. Let us never negotiate out of fear. But let us never fear to negotiate.", author: "John F. Kennedy" },
  { text: "Well done is better than well said. Either write something worth reading or do something worth writing. Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "The journey of a thousand miles begins with a single step. A leader is best when people barely know he exists. When his work is done, his aim fulfilled, they will say: we did it ourselves.", author: "Lao Tzu" },
  { text: "Education is the most powerful weapon which you can use to change the world. It always seems impossible until it is done. The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { text: "Not everything that is faced can be changed, but nothing can be changed until it is faced. The purpose of our lives is to be happy. One of the secrets of a happy life is continuous small treats.", author: "James Baldwin" },
  { text: "I have learned over the years that when one's mind is made up, this diminishes fear; knowing what must be done does away with fear. Life shrinks or expands in proportion to one's courage.", author: "Rosa Parks" },
  { text: "There is nothing permanent except change. No man ever steps in the same river twice, for it is not the same river and he is not the same man. Much learning does not teach understanding.", author: "Heraclitus" },
];
