export interface Quote {
  text: string;
  attribution: string;
}

// 200 most common English words
export const english200: string[] = [
  "the", "be", "to", "of", "and", "a", "in", "that", "have", "i",
  "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
  "this", "but", "his", "by", "from", "they", "we", "her", "she", "or",
  "an", "will", "my", "one", "all", "would", "there", "their", "what", "so",
  "up", "out", "if", "about", "who", "get", "which", "go", "me", "when",
  "make", "can", "like", "time", "no", "just", "him", "know", "take", "people",
  "into", "year", "your", "good", "some", "could", "them", "see", "other", "than",
  "then", "now", "look", "only", "come", "its", "over", "think", "also", "back",
  "after", "use", "two", "how", "our", "work", "first", "well", "way", "even",
  "new", "want", "because", "any", "these", "give", "day", "most", "us", "great",
  "between", "need", "large", "under", "never", "each", "right", "hand", "high", "place",
  "such", "again", "few", "case", "turn", "every", "same", "tell", "does", "set",
  "three", "own", "point", "home", "read", "world", "still", "went", "last", "long",
  "say", "help", "put", "different", "away", "ask", "men", "run", "small", "end",
  "while", "move", "try", "night", "live", "old", "number", "write", "part", "against",
  "keep", "thing", "begin", "where", "life", "much", "many", "before", "start", "might",
  "show", "city", "play", "open", "name", "close", "seem", "together", "next", "group",
  "leave", "change", "room", "call", "water", "side", "been", "head", "house", "school",
  "should", "state", "become", "both", "study", "real", "team", "very", "being", "story",
  "another", "often", "must", "young", "important", "until", "children", "food", "second", "let"
];

// 1000 most common English words (first 200 + 800 more)
export const english1000: string[] = [
  ...english200,
  "money", "once", "free", "power", "public", "face", "water", "body", "music", "color",
  "order", "fire", "south", "problem", "piece", "told", "found", "knew", "since", "family",
  "against", "example", "given", "himself", "felt", "already", "country", "plant", "north", "black",
  "white", "hard", "strong", "feel", "rather", "early", "light", "voice", "inside", "line",
  "low", "outside", "behind", "river", "small", "enough", "across", "later", "four", "five",
  "six", "seven", "eight", "nine", "ten", "hundred", "thousand", "half", "true", "stand",
  "speak", "write", "bring", "hear", "watch", "happen", "send", "fall", "carry", "break",
  "clear", "force", "meet", "check", "past", "cut", "done", "ground", "fine", "cause",
  "least", "full", "between", "special", "able", "upon", "simple", "either", "care", "draw",
  "idea", "rest", "along", "floor", "town", "return", "mind", "heart", "kind", "front",
  "class", "above", "control", "below", "quite", "build", "field", "third", "general", "cover",
  "air", "land", "surface", "material", "note", "single", "though", "certain", "usually", "hold",
  "form", "natural", "common", "period", "pattern", "usually", "result", "question", "answer", "white",
  "person", "almost", "north", "near", "morning", "animal", "friend", "matter", "perhaps", "rule",
  "model", "center", "south", "father", "mother", "always", "often", "never", "certain", "something",
  "nothing", "everything", "everyone", "someone", "anyone", "somewhere", "anywhere", "everywhere", "whenever", "whatever",
  "however", "therefore", "although", "because", "whether", "through", "during", "within", "without", "beyond",
  "toward", "forward", "around", "better", "further", "rather", "almost", "enough", "especially", "exactly",
  "finally", "generally", "however", "including", "instead", "probably", "quickly", "recently", "several", "simply",
  "sometimes", "suddenly", "therefore", "together", "usually", "usually", "various", "already", "another", "because",
  "believe", "between", "cannot", "children", "country", "decided", "different", "during", "everything", "example",
  "following", "himself", "however", "important", "interest", "itself", "language", "little", "money", "morning",
  "mountain", "nothing", "number", "outside", "parents", "picture", "quickly", "really", "remember", "school",
  "second", "should", "someone", "sometimes", "something", "started", "student", "teacher", "through", "together",
  "toward", "trouble", "under", "usually", "wanted", "watch", "water", "where", "whether", "which",
  "while", "white", "whole", "whose", "within", "without", "world", "write", "wrong", "young",
  "across", "almost", "although", "among", "answer", "beautiful", "before", "being", "better", "black",
  "blood", "body", "bright", "broken", "brown", "building", "business", "bought", "called", "came",
  "careful", "carry", "century", "chance", "character", "charge", "church", "clear", "close", "cold",
  "coming", "company", "complete", "corner", "could", "culture", "dead", "death", "deep", "direction",
  "doctor", "doing", "dollar", "door", "dream", "drive", "east", "eight", "energy", "entire",
  "evening", "event", "ever", "every", "exactly", "face", "fact", "fall", "false", "feel",
  "feeling", "floor", "force", "forget", "form", "found", "friend", "game", "garden", "given",
  "glass", "going", "golden", "gone", "government", "great", "green", "grew", "ground", "grow",
  "grown", "guess", "happy", "hard", "heart", "heavy", "help", "history", "home", "hope",
  "hour", "human", "hundred", "idea", "instead", "island", "issue", "itself", "join", "just",
  "kept", "kind", "knew", "knowledge", "land", "later", "learn", "leave", "level", "likely",
  "little", "local", "love", "made", "matter", "maybe", "meeting", "mind", "month", "moon",
  "more", "moving", "music", "nature", "near", "need", "news", "next", "night", "north",
  "nothing", "notice", "object", "office", "once", "open", "order", "others", "outside", "paper",
  "perhaps", "phone", "piece", "plan", "plant", "point", "police", "political", "poor", "power",
  "practice", "present", "pretty", "probably", "process", "program", "provide", "public", "quite", "radio",
  "ready", "reason", "receive", "red", "region", "remain", "report", "require", "rest", "result",
  "return", "right", "river", "road", "short", "simple", "since", "sister", "size", "skin",
  "sleep", "slow", "slowly", "sound", "speak", "spend", "spring", "start", "stay", "step",
  "stop", "store", "street", "strong", "study", "summer", "support", "sure", "table", "talk",
  "teach", "thank", "themselves", "these", "thinking", "thousand", "total", "town", "training", "travel",
  "tree", "truth", "understand", "until", "upon", "usually", "value", "view", "visit", "voice",
  "walk", "wall", "war", "warm", "west", "whole", "wind", "winter", "wish", "woman",
  "word", "working", "worth", "writing", "year", "yesterday", "yourself", "above", "across", "agree",
];

export const quotes: Quote[] = [
  { text: "The only way to do great work is to love what you do. If you have not found it yet keep looking and do not settle.", attribution: "Steve Jobs" },
  { text: "In the middle of every difficulty lies opportunity.", attribution: "Albert Einstein" },
  { text: "It does not matter how slowly you go as long as you do not stop.", attribution: "Confucius" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", attribution: "Eleanor Roosevelt" },
  { text: "Life is what happens when you are busy making other plans.", attribution: "John Lennon" },
  { text: "You must be the change you wish to see in the world.", attribution: "Mahatma Gandhi" },
  { text: "The best time to plant a tree was twenty years ago. The second best time is now.", attribution: "Chinese Proverb" },
  { text: "Do what you can with what you have where you are.", attribution: "Theodore Roosevelt" },
  { text: "Success is not final and failure is not fatal. It is the courage to continue that counts. Every champion was once a contender that refused to give up.", attribution: "Vince Lombardi" },
  { text: "We are what we repeatedly do. Excellence then is not an act but a habit. The things you do every day matter more than what you do once in a while.", attribution: "Aristotle" },
  { text: "Reading is to the mind what exercise is to the body. The more that you read the more things you will know. The more that you learn the more places you will go.", attribution: "Dr. Seuss" },
  { text: "Happiness is not something ready made. It comes from your own actions. Every morning we are born again and what we do today is what matters most.", attribution: "Dalai Lama" },
  { text: "The greatest glory in living lies not in never falling but in rising every time we fall. Life is really simple but we insist on making it complicated. The purpose of our lives is to be happy.", attribution: "Nelson Mandela" },
  { text: "Two roads diverged in a wood and I took the one less traveled by and that has made all the difference.", attribution: "Robert Frost" },
  { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", attribution: "Ralph Waldo Emerson" },
  { text: "In three words I can sum up everything I have learned about life. It goes on.", attribution: "Robert Frost" },
  { text: "Ask not what your country can do for you but ask what you can do for your country.", attribution: "John F. Kennedy" },
  { text: "The way to get started is to quit talking and begin doing. Your time is limited so do not waste it living someone else's life.", attribution: "Walt Disney" },
  { text: "If you look at what you have in life you will always have more. If you look at what you do not have in life you will never have enough.", attribution: "Oprah Winfrey" },
  { text: "If you set your goals ridiculously high and it is a failure you will fail above everyone else's success.", attribution: "James Cameron" },
  { text: "You miss one hundred percent of the shots you do not take.", attribution: "Wayne Gretzky" },
  { text: "Whether you think you can or you think you cannot you are right.", attribution: "Henry Ford" },
  { text: "I have learned that people will forget what you said and people will forget what you did but people will never forget how you made them feel.", attribution: "Maya Angelou" },
  { text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", attribution: "Mother Teresa" },
  { text: "When you reach the end of your rope tie a knot in it and hang on.", attribution: "Franklin D. Roosevelt" },
  { text: "Always remember that you are absolutely unique. Just like everyone else.", attribution: "Margaret Mead" },
  { text: "Do not go where the path may lead. Go instead where there is no path and leave a trail.", attribution: "Ralph Waldo Emerson" },
  { text: "You will face many defeats in life but never let yourself be defeated.", attribution: "Maya Angelou" },
  { text: "The greatest glory in living lies not in never falling but in rising every time we fall.", attribution: "Nelson Mandela" },
  { text: "In the end it is not the years in your life that count but the life in your years.", attribution: "Abraham Lincoln" },
  { text: "Never let the fear of striking out keep you from playing the game.", attribution: "Babe Ruth" },
  { text: "Life is either a daring adventure or nothing at all.", attribution: "Helen Keller" },
  { text: "Many of life's failures are people who did not realize how close they were to success when they gave up.", attribution: "Thomas A. Edison" },
  { text: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", attribution: "Dr. Seuss" },
  { text: "If life were predictable it would cease to be life and be without flavor.", attribution: "Eleanor Roosevelt" },
  { text: "If you want to live a happy life tie it to a goal not to people or things.", attribution: "Albert Einstein" },
  { text: "Never let the fear of striking out keep you from playing the game.", attribution: "Babe Ruth" },
  { text: "Money and success do not change people. They merely amplify what is already there.", attribution: "Will Smith" },
  { text: "Your time is limited so do not waste it living someone else's life. Do not let the noise of others' opinions drown out your own inner voice.", attribution: "Steve Jobs" },
  { text: "Not all those who wander are lost.", attribution: "J.R.R. Tolkien" },
  { text: "It is during our darkest moments that we must focus to see the light.", attribution: "Aristotle" },
  { text: "Whoever is happy will make others happy too.", attribution: "Anne Frank" },
  { text: "Do not judge each day by the harvest you reap but by the seeds that you plant.", attribution: "Robert Louis Stevenson" },
  { text: "The only impossible journey is the one you never begin.", attribution: "Tony Robbins" },
  { text: "In this life we cannot do great things. We can only do small things with great love.", attribution: "Mother Teresa" },
  { text: "Only a life lived for others is a life worthwhile.", attribution: "Albert Einstein" },
  { text: "The purpose of our lives is to be happy.", attribution: "Dalai Lama" },
  { text: "You only live once but if you do it right once is enough.", attribution: "Mae West" },
  { text: "Live in the sunshine swim in the sea drink the wild air.", attribution: "Ralph Waldo Emerson" },
  { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", attribution: "Henry David Thoreau" },
  { text: "When you reach the end of your rope tie a knot in it and hang on.", attribution: "Franklin D. Roosevelt" },
];
