/**
 * Generates lib/memes/templates.ts from template-zones.json and image files.
 *
 * Usage: npx tsx scripts/generate-meme-templates.ts
 */
import fs from "fs";
import path from "path";
import { execSync } from "child_process";

const ZONES_FILE = path.join(process.cwd(), "lib/memes/template-zones.json");
const OUTPUT_FILE = path.join(process.cwd(), "lib/memes/templates.ts");
const MEMES_DIR = path.join(process.cwd(), "public/memes");

// Template display names
const TEMPLATE_NAMES: Record<string, string> = {
  "always-has-been": "Always Has Been",
  "ancient-aliens": "Ancient Aliens",
  "batman-slapping-robin": "Batman Slapping Robin",
  "bike-fall": "Bike Fall",
  "blank-nut-button": "Blank Nut Button",
  "boardroom-meeting": "Boardroom Meeting",
  "change-my-mind": "Change My Mind",
  "cheems": "Buff Doge vs Cheems",
  "disaster-girl": "Disaster Girl",
  "distracted-boyfriend": "Distracted Boyfriend",
  "doge": "Doge",
  "drake": "Drake Hotline Bling",
  "epic-handshake": "Epic Handshake",
  "expanding-brain": "Expanding Brain",
  "gru-plan": "Gru's Plan",
  "hide-the-pain-harold": "Hide the Pain Harold",
  "is-this-a-pigeon": "Is This a Pigeon?",
  "left-exit-12-off-ramp": "Left Exit 12 Off Ramp",
  "mocking-spongebob": "Mocking SpongeBob",
  "one-does-not-simply": "One Does Not Simply",
  "roll-safe": "Roll Safe",
  "running-away-balloon": "Running Away Balloon",
  "success-kid": "Success Kid",
  "surprised-pikachu": "Surprised Pikachu",
  "this-is-fine": "This Is Fine",
  "two-buttons": "Two Buttons",
  "uno-draw-25": "UNO Draw 25",
  "waiting-skeleton": "Waiting Skeleton",
  "woman-yelling-cat": "Woman Yelling at Cat",
  "x-everywhere": "X, X Everywhere",
};

// Preferred template order (most popular first)
const TEMPLATE_ORDER = [
  "drake",
  "distracted-boyfriend",
  "two-buttons",
  "change-my-mind",
  "expanding-brain",
  "woman-yelling-cat",
  "one-does-not-simply",
  "success-kid",
  "is-this-a-pigeon",
  "left-exit-12-off-ramp",
  "running-away-balloon",
  "roll-safe",
  "disaster-girl",
  "batman-slapping-robin",
  "gru-plan",
  "surprised-pikachu",
  "ancient-aliens",
  "mocking-spongebob",
  "boardroom-meeting",
  "blank-nut-button",
  "waiting-skeleton",
  "epic-handshake",
  "x-everywhere",
  "this-is-fine",
  "uno-draw-25",
  "bike-fall",
  "hide-the-pain-harold",
  "doge",
  "cheems",
  "always-has-been",
];

function getImageDimensions(filePath: string): { width: number; height: number } {
  const buf = fs.readFileSync(filePath);

  if (filePath.endsWith(".png")) {
    return {
      width: buf.readUInt32BE(16),
      height: buf.readUInt32BE(20),
    };
  }

  // JPEG
  let offset = 2;
  while (offset < buf.length) {
    if (buf[offset] !== 0xff) break;
    const marker = buf[offset + 1];
    if (marker === 0xc0 || marker === 0xc2) {
      return {
        height: buf.readUInt16BE(offset + 5),
        width: buf.readUInt16BE(offset + 7),
      };
    }
    const segLen = buf.readUInt16BE(offset + 2);
    offset += 2 + segLen;
  }

  throw new Error(`Could not read dimensions of ${filePath}`);
}

interface Zone {
  id: string;
  label: string;
  x: number;
  y: number;
  maxWidth: number;
  maxHeight: number;
  fontSize: number;
  color: string;
  outline: boolean;
  align: "center" | "left";
}

function main() {
  const zones: Record<string, Zone[]> = JSON.parse(
    fs.readFileSync(ZONES_FILE, "utf-8")
  );

  const files = fs
    .readdirSync(MEMES_DIR)
    .filter((f) => /\.(jpg|jpeg|png)$/.test(f));

  const fileMap: Record<string, string> = {};
  for (const f of files) {
    const id = f.replace(/\.(jpg|jpeg|png)$/, "");
    fileMap[id] = f;
  }

  // Build ordered list
  const orderedIds = [
    ...TEMPLATE_ORDER.filter((id) => fileMap[id] && zones[id]),
    ...Object.keys(zones)
      .filter((id) => !TEMPLATE_ORDER.includes(id) && fileMap[id])
      .sort(),
  ];

  let output = `/**
 * Auto-generated by scripts/generate-meme-templates.ts
 * Text zones detected by Claude vision API.
 * Do not edit manually — re-run the script instead.
 */
import type { MemeTemplate } from "@/lib/memes/types";

export const memeTemplates: MemeTemplate[] = [\n`;

  for (const id of orderedIds) {
    const file = fileMap[id];
    const name = TEMPLATE_NAMES[id] || id;
    const src = `/memes/${file}`;
    const filePath = path.join(MEMES_DIR, file);
    const dims = getImageDimensions(filePath);
    const templateZones = zones[id];

    // Convert percentage-based zones to absolute pixel coordinates
    const fields = templateZones.map((z) => ({
      id: z.id,
      label: z.label,
      x: Math.round((z.x / 100) * dims.width),
      y: Math.round((z.y / 100) * dims.height),
      maxWidth: Math.round((z.maxWidth / 100) * dims.width),
      maxHeight: Math.round((z.maxHeight / 100) * dims.height),
      fontSize: z.fontSize,
      color: z.color,
      outline: z.outline,
      align: z.align,
    }));

    output += `  {\n`;
    output += `    id: ${JSON.stringify(id)},\n`;
    output += `    name: ${JSON.stringify(name)},\n`;
    output += `    src: ${JSON.stringify(src)},\n`;
    output += `    width: ${dims.width},\n`;
    output += `    height: ${dims.height},\n`;
    output += `    textFields: [\n`;

    for (const f of fields) {
      output += `      { id: ${JSON.stringify(f.id)}, label: ${JSON.stringify(f.label)}, x: ${f.x}, y: ${f.y}, maxWidth: ${f.maxWidth}, maxHeight: ${f.maxHeight}, fontSize: ${f.fontSize}, color: ${JSON.stringify(f.color)}, outline: ${f.outline}, align: ${JSON.stringify(f.align)} },\n`;
    }

    output += `    ],\n`;
    output += `  },\n`;
  }

  output += `];\n`;

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`Generated ${orderedIds.length} templates → ${OUTPUT_FILE}`);
}

main();
